name: Python package

on:
  schedule:
    - cron: '0 16 * * *'
    - cron: '15 6 26 2 *'
    - cron: '45 6 26 2 *'
    - cron: '15 7 26 2 *'
    - cron: '15 8 26 2 *'
    - cron: '15 9 26 2 *'
    - cron: '15 6 27 2 *'
    - cron: '15 7 27 2 *'
    - cron: '15 8 27 2 *'
    - cron: '15 12 2 3 *'
    - cron: '45 12 2 3 *'
    - cron: '15 6 5 3 *'
    - cron: '45 6 5 3 *'
    - cron: '15 7 5 3 *'
    - cron: '15 9 5 3 *'
    - cron: '15 7 6 3 *'
    - cron: '15 8 6 3 *'
    - cron: '15 9 6 3 *'
    - cron: '15 12 11 3 *'
    - cron: '15 6 12 3 *'
    - cron: '15 7 12 3 *'
    - cron: '15 8 12 3 *'
    - cron: '15 9 12 3 *'
    - cron: '15 10 12 3 *'
    - cron: '45 12 12 3 *'
    - cron: '15 6 13 3 *'
    - cron: '15 7 13 3 *'
    - cron: '15 8 13 3 *'
    - cron: '15 12 18 3 *'
    - cron: '15 6 19 3 *'
    - cron: '15 7 19 3 *'
    - cron: '15 8 19 3 *'
    - cron: '15 9 19 3 *'
    - cron: '15 6 20 3 *'
    - cron: '15 7 20 3 *'
    - cron: '15 6 21 3 *'
    - cron: '15 12 23 3 *'
    - cron: '15 6 26 3 *'
    - cron: '15 7 26 3 *'
    - cron: '15 6 27 3 *'
    - cron: '15 7 27 3 *'
    - cron: '15 8 27 3 *'
    - cron: '45 11 30 3 *'
    - cron: '15 12 30 3 *'
    - cron: '15 12 1 4 *'
    - cron: '15 6 2 4 *'
    - cron: '15 7 2 4 *'
    - cron: '15 8 2 4 *'
    - cron: '15 9 2 4 *'
    - cron: '15 12 2 4 *'
    - cron: '15 6 3 4 *'
    - cron: '15 7 3 4 *'
    - cron: '15 10 3 4 *'
    - cron: '15 11 3 4 *'
    - cron: '15 12 5 4 *'
    - cron: '45 11 6 4 *'
    - cron: '15 12 6 4 *'
    - cron: '45 12 6 4 *'
    - cron: '15 6 9 4 *'
    - cron: '15 7 9 4 *'
    - cron: '15 8 9 4 *'
    - cron: '15 10 9 4 *'
    - cron: '15 12 9 4 *'
    - cron: '15 6 10 4 *'
    - cron: '15 7 10 4 *'
    - cron: '15 8 10 4 *'
    - cron: '15 9 10 4 *'
    - cron: '15 6 16 4 *'
    - cron: '15 7 16 4 *'
    - cron: '15 10 16 4 *'
    - cron: '15 6 17 4 *'
    - cron: '15 7 17 4 *'
    - cron: '15 8 17 4 *'
    - cron: '15 9 17 4 *'
    - cron: '15 10 17 4 *'
    - cron: '15 12 17 4 *'
    - cron: '15 12 20 4 *'
    - cron: '15 12 22 4 *'
    - cron: '15 7 23 4 *'
    - cron: '15 9 23 4 *'
    - cron: '15 10 24 4 *'
    - cron: '45 11 27 4 *'
    - cron: '15 12 27 4 *'
    - cron: '45 12 27 4 *'
    - cron: '15 12 28 4 *'
    - cron: '15 6 29 4 *'
    - cron: '20 6 29 4 *'
    - cron: '15 7 29 4 *'
    - cron: '15 8 29 4 *'
    - cron: '15 9 29 4 *'
    - cron: '15 12 29 4 *'
    - cron: '15 7 30 4 *'
    - cron: '15 9 30 4 *'
    - cron: '15 10 30 4 *'
    - cron: '15 12 30 4 *'
    - cron: '15 6 1 5 *'
    - cron: '15 7 1 5 *'
    - cron: '15 9 1 5 *'
    - cron: '15 7 3 5 *'
    - cron: '15 8 3 5 *'
    - cron: '15 10 3 5 *'
    - cron: '15 6 4 5 *'
    - cron: '15 7 4 5 *'
    - cron: '15 8 4 5 *'
    - cron: '15 9 4 5 *'
    - cron: '15 6 5 5 *'
    - cron: '15 12 6 5 *'
    - cron: '15 7 7 5 *'
    - cron: '15 8 7 5 *'
    - cron: '15 9 7 5 *'
    - cron: '15 10 7 5 *'
    - cron: '15 6 8 5 *'
    - cron: '15 7 8 5 *'
    - cron: '15 8 8 5 *'
    - cron: '15 9 8 5 *'
    - cron: '45 12 13 5 *'
    - cron: '15 6 14 5 *'
    - cron: '15 7 14 5 *'
    - cron: '15 8 14 5 *'
    - cron: '15 9 14 5 *'
    - cron: '15 12 14 5 *'
    - cron: '15 6 15 5 *'
    - cron: '15 7 15 5 *'
    - cron: '15 8 15 5 *'
    - cron: '15 12 15 5 *'
    - cron: '15 12 18 5 *'
    - cron: '45 12 18 5 *'
    - cron: '15 6 21 5 *'
    - cron: '15 7 21 5 *'
    - cron: '15 8 21 5 *'
    - cron: '15 9 21 5 *'
    - cron: '15 10 21 5 *'
    - cron: '15 11 21 5 *'
    - cron: '15 12 21 5 *'
    - cron: '15 7 22 5 *'
    - cron: '15 8 22 5 *'
    - cron: '15 11 25 5 *'
    - cron: '15 12 25 5 *'
    - cron: '45 12 25 5 *'
    - cron: '15 6 28 5 *'
    - cron: '15 7 28 5 *'
    - cron: '15 10 28 5 *'
    - cron: '15 11 28 5 *'
    - cron: '15 5 29 5 *'
    - cron: '15 6 29 5 *'
    - cron: '20 6 29 5 *'
    - cron: '15 7 29 5 *'
    - cron: '15 8 29 5 *'
    - cron: '15 9 29 5 *'
    - cron: '15 10 29 5 *'
    - cron: '15 11 29 5 *'
    - cron: '45 11 29 5 *'
    - cron: '15 12 29 5 *'
    - cron: '15 6 4 6 *'
    - cron: '15 11 4 6 *'
    - cron: '15 6 5 6 *'
    - cron: '15 7 5 6 *'
    - cron: '15 11 5 6 *'
    - cron: '15 12 5 6 *'
    - cron: '15 7 11 6 *'
    - cron: '15 11 11 6 *'
    - cron: '45 11 11 6 *'
    - cron: '15 6 12 6 *'
    - cron: '15 7 12 6 *'
    - cron: '15 9 12 6 *'
    - cron: '15 11 12 6 *'
    - cron: '15 12 15 6 *'
    - cron: '15 7 18 6 *'
    - cron: '15 10 18 6 *'
    - cron: '15 11 18 6 *'
    - cron: '15 12 18 6 *'
    - cron: '15 6 19 6 *'
    - cron: '15 7 19 6 *'
    - cron: '15 9 19 6 *'
    - cron: '15 11 19 6 *'
    - cron: '15 9 25 6 *'
    - cron: '15 10 25 6 *'
    - cron: '15 11 25 6 *'
    - cron: '45 11 25 6 *'
    - cron: '15 12 25 6 *'
    - cron: '15 7 26 6 *'
    - cron: '15 8 26 6 *'
    - cron: '45 9 26 6 *'
    - cron: '15 11 26 6 *'
    - cron: '45 11 26 6 *'
    - cron: '15 12 26 6 *'
    - cron: '15 7 2 7 *'
    - cron: '15 8 2 7 *'
    - cron: '45 9 2 7 *'
    - cron: '15 10 2 7 *'
    - cron: '15 11 2 7 *'
    - cron: '45 11 2 7 *'
    - cron: '15 12 2 7 *'
    - cron: '45 12 2 7 *'
    - cron: '15 9 3 7 *'
    - cron: '15 11 3 7 *'
    - cron: '15 12 3 7 *'
    - cron: '15 11 6 7 *'
    - cron: '15 12 6 7 *'
    - cron: '45 12 6 7 *'
    - cron: '15 9 9 7 *'
    - cron: '15 10 9 7 *'
    - cron: '15 11 9 7 *'
    - cron: '45 11 9 7 *'
    - cron: '15 12 9 7 *'
    - cron: '15 7 10 7 *'
    - cron: '15 11 10 7 *'
    - cron: '15 12 10 7 *'
    - cron: '15 12 15 7 *'
    - cron: '45 9 16 7 *'
    - cron: '15 11 16 7 *'
    - cron: '45 11 16 7 *'
    - cron: '15 12 16 7 *'
    - cron: '15 8 17 7 *'
    - cron: '45 9 17 7 *'
    - cron: '15 11 17 7 *'
    - cron: '45 11 17 7 *'
    - cron: '15 12 17 7 *'
    - cron: '15 12 18 7 *'
    - cron: '15 9 23 7 *'
    - cron: '45 9 23 7 *'
    - cron: '15 10 23 7 *'
    - cron: '15 11 23 7 *'
    - cron: '15 12 23 7 *'
    - cron: '15 10 24 7 *'
    - cron: '15 11 24 7 *'
    - cron: '15 12 24 7 *'
    - cron: '15 12 27 7 *'
    - cron: '15 7 30 7 *'
    - cron: '15 10 30 7 *'
    - cron: '15 11 30 7 *'
    - cron: '45 11 30 7 *'
    - cron: '15 12 30 7 *'
    - cron: '15 8 31 7 *'
    - cron: '15 11 31 7 *'
    - cron: '15 12 31 7 *'
    - cron: '15 11 6 8 *'
    - cron: '45 11 6 8 *'
    - cron: '15 12 6 8 *'
    - cron: '15 11 7 8 *'
    - cron: '15 12 7 8 *'
    - cron: '15 7 13 8 *'
    - cron: '15 9 13 8 *'
    - cron: '15 11 13 8 *'
    - cron: '45 11 13 8 *'
    - cron: '15 12 13 8 *'
    - cron: '15 9 14 8 *'
    - cron: '15 10 14 8 *'
    - cron: '15 11 14 8 *'
    - cron: '45 11 14 8 *'
    - cron: '15 12 14 8 *'
    - cron: '45 12 19 8 *'
    - cron: '15 7 20 8 *'
    - cron: '45 9 20 8 *'
    - cron: '15 11 20 8 *'
    - cron: '45 11 20 8 *'
    - cron: '15 12 20 8 *'
    - cron: '15 8 21 8 *'
    - cron: '15 9 21 8 *'
    - cron: '15 10 21 8 *'
    - cron: '15 11 21 8 *'
    - cron: '15 12 21 8 *'
    - cron: '15 12 26 8 *'
    - cron: '15 10 27 8 *'
    - cron: '15 11 27 8 *'
    - cron: '45 11 27 8 *'
    - cron: '15 12 27 8 *'
    - cron: '15 8 28 8 *'
    - cron: '15 11 28 8 *'
    - cron: '15 12 28 8 *'
    - cron: '45 12 28 8 *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set git config
      run: |
        git config --global user.name "mokekuma-git"
        git config --global user.email "mokekuma.git@gmail.com"
    - name: git checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: "requirements.txt"
    - name: Update matches json
      run: |
        DATE=`TZ=JST-9 date +'%m/%d %H:%M'`
        python src/read_jleague_matches.py
        if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "Make new csv & json (append games on $DATE)"; \
            git push origin HEAD; \
        fi
