# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set current date as env variable
      run: echo "NOW::$(date +'%m/%d')" >> $DATE
    - name: Update matches json
      run: |
        git config --global user.name "mokekuma-git"
        git config --global user.email "mokekuma.git@gmail.com"
        git checkout data/match/update
        git pull
        RESULT=`python src/read_jleague_matches.py`
        git add .
        git commit -m "Make new csv & json (append games on $DATE)\n$RESULT"
        git push
